"""empty message

Revision ID: 1382043dfa04
Revises: 2807edd385a2
Create Date: 2021-12-28 01:12:24.833320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1382043dfa04'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psicologo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('direccion_comercial', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion_comercial'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psicologo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('diagnóstico', sa.String(length=120), nullable=True),
    sa.Column('estado_civil', sa.String(length=120), nullable=True),
    sa.Column('nro_hijos', sa.Integer(), nullable=True),
    sa.Column('nacionalidad', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['psicologo_id'], ['psicologo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnóstico'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('estado_civil'),
    sa.UniqueConstraint('nacionalidad'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nro_hijos')
    )
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respuesta', sa.String(length=120), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('respuesta')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('bot')
    op.drop_table('paciente')
    op.drop_table('psicologo')
    # ### end Alembic commands ###
