"""empty message

Revision ID: 67286edd5386
Revises: 3a6df389b140
Create Date: 2022-01-14 03:24:40.632208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67286edd5386'
down_revision = '3a6df389b140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('diagnostico', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial')
    # ### end Alembic commands ###
