"""empty message

Revision ID: 92b15a67bed8
Revises: 475480f9067e
Create Date: 2021-12-28 02:11:54.320794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b15a67bed8'
down_revision = '475480f9067e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('telefono', sa.String(length=12), nullable=False))
    op.create_unique_constraint(None, 'paciente', ['telefono'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paciente', type_='unique')
    op.drop_column('paciente', 'telefono')
    # ### end Alembic commands ###
